name: HelloKishan
description: HelloKishan
version: 1.0.2+3

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore:
  firebase_admob:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  firebase_storage:
  firestore_ui:

  carousel_slider:
  curved_navigation_bar:
  easy_localization:
  flutter_typeahead:
  image_cropper:
  image_picker:
  intl:
  introduction_screen:
  shared_preferences:
  url_launcher:
  animated_stream_list:

  geocoder:
  geoflutterfire:
  geolocator:
  provider:
  upi_pay:

environment:
  sdk:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/translations/
  uses-material-design: true
