name: FarmApp
description: FarmApp
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  firebase_core:
  firebase_auth:
  firebase_auth_web:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:

  #shimmer:
  #octo_image:
  image_cropper:
  image_picker:
  introduction_screen:
  intl:

  geocoder:
  geoflutterfire:
  location:

  provider:
  animated_stream_list:

  url_launcher: ### Starting Phone/Mail Activities ###

  curved_navigation_bar:
  flutter_typeahead:
  progress_dialog:
  splashscreen:
  shared_preferences:

environment:
  sdk:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true ### Material Icons Font ###
