name: FarmApp
description: FarmApp
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  firebase_core:
  firebase_auth:
  firebase_auth_web:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  firebase_image:

  shimmer:
  octo_image:
  image_cropper:
  transparent_image:
  image_picker:
  pin_entry_text_field:

  geolocator:
  geocoder:
  geoflutterfire:

  flutter_bloc:
  provider:

  stack_trace: ### For DEBUG purpose only ###
  universal_html:
  url_launcher: ### Starting Phone/Mail Activities ###

  animated_text_kit:
  numeric_keyboard:
  curved_navigation_bar:
  cupertino_icons:
  flutter_spinkit:
  flutter_typeahead:
  progress_dialog:
  splashscreen:
  loading_gifs:
  shared_preferences:

  flutter_mobx:
  mobx:
  flutter_libphonenumber:

environment:
  sdk:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:

flutter:
  assets:
    - assets/images/
  uses-material-design: true ### Material Icons Font ###
