name: FarmApp
description: FarmApp
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore:
  firebase_admob:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  firebase_storage:
  firestore_ui:

  curved_navigation_bar:
  easy_localization:
  flutter_typeahead:
  image_cropper:
  image_picker:
  intl:
  introduction_screen:
  progress_dialog:
  shared_preferences:
  url_launcher:

  geocoder:
  geoflutterfire:
  geolocator:
  provider:

environment:
  sdk:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/translations/
  uses-material-design: true
