name: farmapp
description: FarmApp
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore:
  firebase_core:
  firebase_analytics:
  firebase_auth:
  firebase_auth_web:
  firebase_storage:
  firebase_image:

  cupertino_icons:
  flutter_spinkit:
  geolocator:
  image_picker:
  provider:
  shared_preferences:
  splashscreen:
  universal_html:
  validate:
  flutter_typeahead:

environment:
  sdk:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/app_logo.jpg
  uses-material-design: true # Material Icons Font
